package:
  name: exceptional
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  number: 0
  string: {{ environ.get('GIT_BUILD_STR', '') }}_py{{ py }}
  command: python setup.py install --single-version-externally-managed --record=/dev/null

requirements:
  build:
    - python
  run:
    - ipython
    - python
    - requests

test:
  imports:
    - exceptional

about:
  home: http://github.com/nsls-ii/exceptional
  license: 3-Clause BSD
